/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PaqueteA;


import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.text.ParseException;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;


/**
 * @author JoaCa
 */
public class frmFormulario1 extends javax.swing.JInternalFrame {
    
    Calendar fecha = new GregorianCalendar();
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row,int column){
            return false;
        }
    };  
    
     
    public frmFormulario1() {
        initComponents();

        jdcFecha.setDate(fecha.getTime());

        //********************TABLA***************************
        tblDatos.setModel(modelo);
        //AGREGANDO 3 COLUMNAS AL MODELO
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha");
        //AGREGANDO 2 FILAS
        Object[] fila = new Object[3];
        fila[0] = "001";
        fila[1] = " Claudio Jimenes Castro";
        fila[2] = "18/11/1993";
        modelo.addRow(fila);

        fila[0] = "002";
        fila[1] = "Derick Gutierrez Mejias";
        fila[2] = "12/06/1995";
        modelo.addRow(fila);
        
        fila[0] = "003";
        fila[1] = "Jaen Gonzalez Arauz";
        fila[2] = "12/06/1999";
        modelo.addRow(fila);
        
        fila[0] = "004";
        fila[1] = "Javier Bolanos Ramirez";
        fila[2] = "12/06/1998";
        modelo.addRow(fila);
        
        fila[0] = "005";
        fila[1] = "Mariel Rojas Sanchez";
        fila[2] = "12/06/1997";
        modelo.addRow(fila);
        
        fila[0] = "006";
        fila[1] = "Maureen Gabriela Gutierrez";
        fila[2] = "12/06/1996";
        modelo.addRow(fila);

        this.closable = true;
    }//fin

    public void CargarDatos() {
        Object[] fila = new Object[3];

        if (!txtID.getText().equals("") && !txtNombre.getText().equals("")) {
            fila[0] = txtID.getText();
            fila[1] = txtNombre.getText();
            fila[2] = new SimpleDateFormat("dd/MM/yyyy").format(jdcFecha.getDate());
            modelo.addRow(fila);
        } else {
            JOptionPane.showMessageDialog(this, "Faltan Datos");
        };
    }
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        cboPersonas = new javax.swing.JComboBox<>();
        btnCargar = new javax.swing.JButton();
        txtPersona = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de Datos");

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jdcFecha.setDateFormatString("dd/MM/yyyy");

        jLabel3.setText("Fecha de Nacimiento");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        cboPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPersonasActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPersona)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cboPersonas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(85, 85, 85)
                        .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar))
                .addGap(18, 18, 18)
                .addComponent(txtPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
       DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        cboPersonas.setModel(modeloCombo);
        
        //recorrer la tabla
        for (int i = 0; i < tblDatos.getRowCount(); i++) {
            modeloCombo.addElement(new Persona(Integer.parseInt(tblDatos.getValueAt(i, 0).toString()),tblDatos.getValueAt(i,1 ).toString()));
        }
        
        cboPersonas.setSelectedIndex(-1); // para que el combo aparezca vacio
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        CargarDatos();
        txtID.setText(null);
        txtNombre.setText(null);
        jdcFecha.setDate(fecha.getTime());
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        //no existe un evento doble clic pero se puede simular
        
        if (evt.getClickCount() == 2) { //si se dio doble clic 
            
            int fila = tblDatos.rowAtPoint(evt.getPoint());
            
            txtID.setText(tblDatos.getValueAt(fila, 0).toString());
            
            txtNombre.setText(tblDatos.getValueAt(fila, 1).toString());
            
            String fechaTexto = tblDatos.getValueAt(fila, 2).toString();
            
            try {
                Date fechaDate = formato.parse(fechaTexto);
                jdcFecha.setDate(fechaDate);
            } catch (ParseException ex) {
                //sabemos que es un error de conversion, por eso no usamos el generico exeption, sino perse exeption
                JOptionPane.showMessageDialog(this, "Error al recuperar la fecha:" + ex.getMessage());
            }            
        }
    }//GEN-LAST:event_tblDatosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // 1. crear la instancia del formulario de busqueda
        dlgBuscar1 buscar = new dlgBuscar1(null, true);
       /*
        el primer parametro es el propietario, como es internal no puede ser propietario de nadie
        el segundo parametro es si es un formulario modal, es este caso si lo es
        */
       
       //2. sobreescribir el metodo de cerrar
        /*
        es similar a cuando en javascript se creaba un add event listener,
        que estaba atento esperando un evento.
        */
        buscar.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosed(WindowEvent e){
                /*
                recuperar cual fue la fila seleccionada, el cual recupera
                el dato que estaba en el cuadro de texto.
                */
                int fila = buscar.ObtenerId();
                
                // el dato de la fila seleccionada, primera columna (0)   
                txtID.setText(tblDatos.getValueAt(fila, 0).toString());
                // el dato de la fila seleccionada, segunda columna (1)  
                txtNombre.setText(tblDatos.getValueAt(fila, 1).toString()); 
                /*
                la fecha la asignamos al calendario
                (copiamos del metodo tblDatomouseclicked)
                */
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                // el dato de la fila seleccionada,tercera columna
                String fechaTexto = tblDatos.getValueAt(fila, 2).toString();
                try {
                    Date fechaDate = formato.parse(fechaTexto);
                    jdcFecha.setDate(fechaDate);
                } catch (ParseException ex) {
                    //sabemos que es un error de conversion, por eso no usamos el generico exeption, sino perse exeption
                    JOptionPane.showMessageDialog(null, "Error al recuperar la fecha:" + ex.getMessage());
                    // en lugar de this (el cuadro de dialogo), le asignamos null
                }                
            }      
        });
        //3. mostrar el formulario
        buscar.setVisible(true);//mostrarmos el modal   
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cboPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPersonasActionPerformed
            if (cboPersonas.getSelectedIndex() != -1) {
            // en cada elemento del combo hay un objeto tipo persona, tomamos el objeto y lo comvertimos en un objeto tipo persona
            Persona p1 = (Persona) cboPersonas.getSelectedItem();
            
            txtPersona.setText(String.valueOf(p1.getId())+". "+p1.getNombre());          
        }
        else{
            txtPersona.setText(null);
        }
    }//GEN-LAST:event_cboPersonasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFormulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFormulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFormulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFormulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFormulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JComboBox<String> cboPersonas;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPersona;
    // End of variables declaration//GEN-END:variables
}
